# site settings
title: Mustafa GUNES
subtitle: Developer
email: gunes149@gmail.com
description: Blog siteme hoşgeldin!<br /> Yazılarımı okumak ister misin?
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 8019. Cadde
city: Gaziantep
state: TR
zip_code: 27500
country: Türkiye
phone: 0 (542) 528-6341

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/gunesim.soft
github_url: https://github.com/mustafagunes
gitlab_url: https://gitlab.com/mustafagunes
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com/mustafagunes_1
linkedin_url: https://www.linkedin.com/in/mustafagunes1
pinterest_url:
slack_url:
twitter_url: https://twitter.com/bashreks

# build settings
markdown: kramdown

sass:
  style: compressed

gems:
- jekyll-admin